name: auto_asistan
description: "AutoAssist - Dijital Araç Asistanı"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.8.0

  # Navigation
  go_router: ^14.0.0

  # UI & Animation
  google_fonts: ^6.2.0
  flutter_animate: ^4.5.0


  # Map
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

  # Location & Permissions
  geolocator: ^13.0.0
  permission_handler: ^11.3.0

  # HTTP & API
  http: ^1.2.0

  # Local Storage
  shared_preferences: ^2.3.0

  # Notifications
  flutter_local_notifications: ^18.0.0

  # Utility
  intl: ^0.20.2
  uuid: ^4.4.0
  image_picker: ^1.1.0
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.2.1
  iconoir_flutter: ^7.11.0
  flutter_chat_ui: ^2.11.1
  settings_ui: ^2.0.2
  flutter_chat_types: ^3.6.2
  flutter_chat_core: ^2.9.0
  liquid_glass_renderer: ^0.2.0-dev.4
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - .env
